# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openforum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id_fk',
            new_name='answer_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id_fk',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id_fk',
            new_name='question_author',
        ),
        migrations.AddField(
            model_name='answer',
            name='vote_down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='vote_up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_up_count',
            field=models.IntegerField(default=0),
        ),
    ]
